services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "9000:9000"
      - "19888:19888"
      - "9092:9092"
      - "2181:2181"
    networks:
      - hadoop
    volumes:
      - ~/documents/Big Data/kafka_project:/shared_volume
      - kafka-logs:/tmp/kafka-logs
    environment:
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    stdin_open: true
    tty: true

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"
      - "9093:9093"
    networks:
      - hadoop
    volumes:
      - ~/documents/Big Data/kafka_project:/shared_volume
      - kafka-logs-1:/tmp/kafka-logs-1
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"
      - "9094:9094"
    networks:
      - hadoop
    volumes:
      - ~/documents/Big Data/kafka_project:/shared_volume
      - kafka-logs-2:/tmp/kafka-logs-2
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master

networks:
  hadoop:
    driver: bridge

volumes:
  kafka-logs:
    driver: local
  kafka-logs-1:
    driver: local
  kafka-logs-2:
    driver: local